### ISSUE TITLE
Strategy

### ISSUE THREAD

**Issue by PaulaPeraltaA** [bkthomps/Ajedrez#12]
En el juego de ajedrez la implementación de las piezas es casi idéntica entre ellas pero lo que las diferencia es su movimiento, por lo que tiene un algoritmo que tiende a sufrir cambios frecuentes. Para lidiar correctamente con esto se debe utilizar el  patrón estructural Strategy que logra intercambiar este algoritmo durante el tiempo de ejecución y evitar cambiar el contexto al introducir nuevas estrategias.

**Comment by bkthomps** [comment]
@PaulaPeraltaA Gracias por su comentario, pero ¿cuál es su sugerencia?

Estoy usando el algoritmo minimax con poda alfa-beta. La heurística tiene 3 partes: 1. las piezas (y peones) que quedan por cada color, 2. la posición de las piezas (y peones), 3. derechos de enroque
